### ISSUE TITLE
CFBundleExecutable value being set in SatisMeter's resource bundle

### ISSUE THREAD

**Issue by jsedlacek** [satismeter/satismeter-ios#10]
Reported by customer:

> We had another test error I forgot to mention: uploading to iTunes Connect failed because of the CFBundleExecutable value being set in SatisMeter's resource bundle.

**Comment by adriencog** [comment]
Hi,
We need this bug to be fixed so we can integrate satismeter in our app.
Thanks!

**Comment by jsedlacek** [comment]
Thanks for letting us know @AdrienCog. We will have this fixed for the next release (mid-August).

**Comment by jsedlacek** [comment]
@AdrienCog we have fixed this issue in `0.2.5` version. Please let me know if you have any other issues.
