### ISSUE TITLE
Library not compatible with Bitcode-enabled apps

### ISSUE THREAD

**Issue by jpgupta** [satismeter/satismeter-ios#15]
Hi guys - been using Satismeter on my website for a while and would like to integrate it onto iOS. I'm getting an error when trying to archive the project with the Satismeter cocooapods installed saying it can't be exported because it isn't bitcode enabled - see this SO post for reference: http://stackoverflow.com/questions/34666247/bitcode-bundle-could-not-be-generated-because-ios-charts

I think just building a new version of the framework in XCode 7 should solve the issue

**Comment by jsedlacek** [comment]
@jpgupta Thanks for reporting this. Let us have a look what can we do with it.

**Comment by jsedlacek** [comment]
@jpgupta Fixed in version 0.2.9. Sorry it took longer than expected.
