### ISSUE TITLE
Position of survey box

### ISSUE THREAD

**Issue by luciovinicius** [satismeter/satismeter-ios#18]
is there a way to show the survey box on top or in the middle? it works on web but not in sdk. Can anyone help me?

**Comment by jsedlacek** [comment]
@luciovinicius Hello, there is currently no way to change to position with our mobile SDK. What is the reason you'd like to show it elsewhere?

**Comment by jsedlacek** [comment]
Closing, the survey is currently always shown on the bottom of the screen for convenience.
