### ISSUE TITLE
Typed text is invisible in dark mode

### ISSUE THREAD

**Issue by petrlz63** [satismeter/satismeter-ios#19]
When i'm in dark mode and start typing, then text is invisible.

**Comment by petrlz63** [comment]
![Image from iOS](https://user-images.githubusercontent.com/31001678/74239605-7488f100-4cd8-11ea-9f4b-cc643a2a32f9.png)

**Comment by jsedlacek** [comment]
@petrlz63 Thanks for a bug report. This should be fixed in version 0.2.11.

See https://github.com/satismeter/satismeter-ios/blob/master/CHANGELOG.md
