### ISSUE TITLE
.framework installation instructions doesn't work

### ISSUE THREAD

**Issue by wangjiejacques** [satismeter/satismeter-ios#21]
the alias **Framework/SatisMeter.framework/SatisMeter** link to **Versions/Current/SatisMeter**, but this file doesn't even exists.

**Comment by jsedlacek** [comment]
@wangjiejacques Thanks for reporting. Let us have a look.

**Comment by wangjiejacques** [comment]
Hi @jsedlacek , can you tell me when will you give us a feedback? if it's too long, we have to give up this solution.

**Comment by jsedlacek** [comment]
I have passed this to the team. I hope to have a solution early next week.

**Comment by jsedlacek** [comment]
Update: we are working on a fix. Should be ready in a couple of days.

**Comment by antongorb** [comment]
Hi @wangjiejacques, is this issue actual for you?
