### ISSUE TITLE
Is there a way for cancel the satismeter when user logout?

### ISSUE THREAD

**Issue by sainttail** [satismeter/satismeter-ios#23]
We only add satismeter during user logged in only so that mean we call `identifyUser:` after the logged in.

But I can't seem to find a way to clear this `identifyUser:` when logged out.

**Comment by jsedlacek** [comment]
@sainttail Currently, there is no way to clear the user.

We're only identifying and checking the survey targeting only once right after the `identifyUser` is called. Thus, clearing after logout should not be needed.
